---
- name: Set up Apache web server
  hosts: webservers
  become: yes
  tasks:

    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache (Debian/Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Create a simple HTML page
      ansible.builtin.copy:
        content: "<html><body><h1>Welcome to my web server!</h1></body></html>"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

    - name: Open HTTP port in firewall (RedHat)
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
      when: ansible_os_family == "RedHat"

    - name: Open HTTP port in firewall (Debian/Ubuntu)
      ansible.builtin.ufw:
        rule: allow
        port: 80
        proto: tcp
      when: ansible_os_family == "Debian"
